-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 16:41:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema showcase
-- -----------------------------------------------------
-- DMS databases schema
DROP SCHEMA IF EXISTS `showcase` ;

-- -----------------------------------------------------
-- Schema showcase
--
-- DMS databases schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `showcase` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `showcase` ;

-- -----------------------------------------------------
-- Table `showcase`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`USERS` ;

CREATE TABLE IF NOT EXISTS `showcase`.`USERS` (
  `LOGIN_ID` VARCHAR(45) NULL,
  `USER_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `PASSWORD` VARCHAR(10) NULL,
  `EMAIL_ID` VARCHAR(70) NOT NULL,
  `ORG_NAME` VARCHAR(50) NULL,
  `FIRST_NAME` VARCHAR(50) NULL,
  `LAST_NAME` VARCHAR(50) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `showcase`.`ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `showcase`.`ORGANIZATION` (
  `ORGANIZATION_ID` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT 'This table maintains the dace information of organization / Company / Individual',
  `ORG_NAME` VARCHAR(45) NULL,
  `ORG_TYPE` VARCHAR(45) NULL,
  `USER_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`ORGANIZATION_ID`),
  CONSTRAINT `fk_ORGANIZATION_USERS`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `showcase`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `showcase`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `showcase`.`PRODUCT` (
  `PRODUCT_ID` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `PRODUCT_NAME` VARCHAR(45) NOT NULL COMMENT 'Product Name ',
  `DESCRIPTION` VARCHAR(100) NULL COMMENT 'Product Description',
  `PRODUCT_CODE` VARCHAR(100) NULL COMMENT 'This column can be used to maintain the products uniqued id main by Organization in their system.\n\nThis can be numeric, alphanumeric , alphabets in said organization, we need to decide , how we can use it effectively',
  `ORGANIZATION_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  CONSTRAINT `fk_PRODUCT_ORGANIZATION1`
    FOREIGN KEY (`ORGANIZATION_ID`)
    REFERENCES `showcase`.`ORGANIZATION` (`ORGANIZATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `showcase`.`PRODUCT_DOC_CONF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`PRODUCT_DOC_CONF` ;

CREATE TABLE IF NOT EXISTS `showcase`.`PRODUCT_DOC_CONF` (
  `PR_DOC_CONF_ID` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `PRODUCT_ID` BIGINT(10) NULL COMMENT 'References to Product Table ',
  `DESCRIPTION` VARCHAR(45) NULL COMMENT 'Description of this document type',
  `IS_MANDATORY` TINYINT(1) NULL COMMENT 'determines if this documendatory for this type of product configuration',
  `GROUP_ID` INT NULL COMMENT 'Not decided use of this column, but idea is to maintain the group of documents for given product configuration',
  `DISPLAY_SEQ` INT NULL COMMENT 'Display sequence of image',
  `PRODUCT_DOC_TYPE_CODE` VARCHAR(10) NULL,
  PRIMARY KEY (`PR_DOC_CONF_ID`),
  CONSTRAINT `fk_PRODUCT_DOC_CONF_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `showcase`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'This table maintains the documents configurations for the given product.';


-- -----------------------------------------------------
-- Table `showcase`.`PRODUCT_DOC_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`PRODUCT_DOC_TYPE` ;

CREATE TABLE IF NOT EXISTS `showcase`.`PRODUCT_DOC_TYPE` (
  `PRODUCT_DOC_TYPE_CODE` VARCHAR(10) NOT NULL COMMENT 'This code determines document type, such as PDF, IMAGE, VIDEO and So on',
  `DESCRIPTION` VARCHAR(45) NULL)
ENGINE = InnoDB
COMMENT = 'Product Document types, This can be used as lookup Table ';


-- -----------------------------------------------------
-- Table `showcase`.`IMG_DOC_CONF_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`IMG_DOC_CONF_DETAILS` ;

CREATE TABLE IF NOT EXISTS `showcase`.`IMG_DOC_CONF_DETAILS` (
  `CONF_DETAILS_ID` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `PRODUCT_DOC_CONF_ID` BIGINT(10) NULL COMMENT 'References to PRODUCT_DOC_CONF table',
  `IMAGE_FORMAT` VARCHAR(10) NULL COMMENT 'IMAGE_TYPE as JPEG, GIF, aCurrently only JPEG supported',
  `IMAGE_HEIGHT` INT NULL,
  `IMAGE_WIDTH` INT NULL,
  PRIMARY KEY (`CONF_DETAILS_ID`))
ENGINE = InnoDB
COMMENT = 'This table data elaborates the Image document type configuration details';


-- -----------------------------------------------------
-- Table `showcase`.`PRODUCT_DOCUMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showcase`.`PRODUCT_DOCUMENTS` ;

CREATE TABLE IF NOT EXISTS `showcase`.`PRODUCT_DOCUMENTS` (
  `PRODUCT_DOC_ID` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `PRODUCT_ID` BIGINT(10) NULL COMMENT 'References to Product table',
  `PRODUCT_DOC_CONF_ID` BIGINT(10) NULL COMMENT 'References to the PRODUCT_DOC_CONF table',
  `URL` VARCHAR(200) NULL COMMENT 'Document URL',
  `SEQ_NO` INT NULL COMMENT 'Sequence no of document. Where is the proper place of this attribute, in this table or PRODUCT Doc configuration table.',
  PRIMARY KEY (`PRODUCT_DOC_ID`))
ENGINE = InnoDB
COMMENT = 'This table contains the product Documents instances as per configurations';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
